
# Site settings
title: Cooking With Gas
email: budaitraveller2@gmail.com
description: A blog exploring Smart Contract development and analysis. 
baseurl: "/cookingwithgas" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username: budaitraveller

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
