# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cooking With Gas
email: budaitraveller2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notes and memoirs from a team developing and analyzing smart contracts.
baseurl: "/cookingwithgas" # the subpath of your site, e.g. /blog
url: "https://budaitraveller.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: budaitraveller

# Build settings
markdown: kramdown
